title = "Home - Esthetic & Beauty Services"
description = "Lorem Ipsum"
languageCode = "en-ca"
baseURL = "/"
DefaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
gtm = "#"
servicename = "Lea Chanel Beauty"
googlemap = "#"
sitename = "Lea Chanel Beauty"
usebasin = "#"
videoOn = false
description = "Lorem ipsum"

[params.schema]
ogimage = "/img/lea_chanel_oggraph.jpg"
logofooter = "/img/leachanel-1-.jpg"
city = "Rigaud"
logo = "/img/leachanel-1-.jpg"
reservation = true
phone = "(438) 929-1556"
priceRange = "$$$"
region = "QC"
country = "Canada"
postalcode = "J0P 1P0"
type = "BeautySalon"
openinghour = "Mo-Sa: 10-6"
email = "lea@leachanelbeauty.com"
address1 = "205 Chemin du Grand Quai"
address2 = "#"
address_toggle = true

[params.social]
facebook = "https://facebook.com/leachanelbeauty/"
twitter = "#"
pinterest = "#"
instagram = "https://www.instagram.com/lea.chanel.beauty/"
linkedin = "#"

[[params.hours]]
hours = "Mon to Fri: 9AM to 7PM"

[[params.hours]]
hours = "Sat: CLOSED"

[[params.hours]]
hours = "Sun: CLOSED"

[module]

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "./node_modules/alpinejs/dist/alpine.js"
target = "assets/js/alpine.js"

[[module.mounts]]
source = "./node_modules/lazysizes/lazysizes.js"
target = "assets/js/lazysizes.js"

[[module.mounts]]
source = "./node_modules/aos/dist/aos.js"
target = "assets/js/aos.js"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[build]
writeStats = true
enableRobotsTXT = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = "1"

[[menu.main]]
name = "About"
url = "about/"
weight = "2"

[[menu.main]]
name = "Gallery"
url = "gallery/"
weight = "3"

[[menu.main]]
name = "Services"
url = "services/"
weight = "4"

[[menu.main]]
name = "Contact"
url = "contact/"
weight = "5"

[[menu.main]]
name = "Appointment"
url = "/"
weight = "6"