baseURL = "https://www.leachanelbeauty.com/"
languageCode = "en-ca"
DefaultContentLanguage = "en"
enableRobotsTXT = true
disableAliases = true
disableKinds = ["categories", "tags"]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"

[build]
writeStats = true

[params]
gtm = "GTM-5DLMNCL"
servicename = "Léa Chanel Esthetic & Beauty Services in Rigaud, QC"
googlemap = "#"
sitename = "Léa Chanel Esthetic & Beauty Services in Rigaud, QC"
usebasin = "#"
videoOn = false
description = "#"

[params.schema]
ogimage = "/img/home_gallery_5.jpg"
logofooter = "/img/leachanel-1-.jpg"
city = "Rigaud"
logo = "/img/leachanel-1-.jpg"
reservation = true
phone = "(438) 929-1556"
priceRange = "$$$"
region = "QC"
country = "Canada"
postalcode = "J0P 1P0"
type = "BeautySalon"
openinghour = "Mo-Sa: 10-6"
email = "lea@leachanelbeauty.com"
address1 = "205 Chemin du Grand Quai"
address2 = "#"
address_toggle = true

[params.social]
facebook = "https://facebook.com/leachanelbeauty/"
twitter = "#"
pinterest = "#"
instagram = "https://www.instagram.com/lea.chanel.beauty/"
linkedin = "#"

[[params.hours]]
hours = "Mon to Fri: 9AM to 7PM"

[[params.hours]]
hours = "Sat: CLOSED"

[[params.hours]]
hours = "Sun: CLOSED"

[module]

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "./node_modules/alpinejs/dist/alpine.js"
target = "assets/js/alpine.js"

[[module.mounts]]
source = "./node_modules/lazysizes/lazysizes.js"
target = "assets/js/lazysizes.js"

[languages]

[languages.fr]
title = "Léa Chanel Services D'Esthétique à Rigaud, QC"
description = "Services professionnels d'esthétique et de beauté offerts dans un salon privé chic et confortable."
languageCode = "fr"
contentDir = "content/fr"

[languages.fr.menu]

[[languages.fr.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[languages.fr.menu.main]]
name = "À Propos"
url = "a-propos/"
weight = 2

[[languages.fr.menu.main]]
name = "Gallerie"
url = "gallerie/"
weight = 3

[[languages.fr.menu.main]]
name = "Produits"
url = "produits/"
weight = 4

[[languages.fr.menu.main]]
name = "Services"
url = "services/"
weight = 5

[[languages.fr.menu.main]]
name = "Contact"
url = "contact/"
weight = 6

[[languages.fr.menu.main]]
name = "Rendez-vous"
url = "https://squareup.com/appointments/book/lkzsutw147ekig/LS5KRH7VEZTBB/services"
weight = 7

[languages.en]
title = "Léa Chanel Esthetic & Beauty Services in Rigaud, QC"
description = "Professional esthetic and beauty services offered in a chic and beautiful private home salon. "
languageCode = "en"
contentDir = "content/en"

[languages.en.menu]

[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = "1"

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = "2"

[[languages.en.menu.main]]
name = "Gallery"
url = "gallery/"
weight = "3"

[[languages.en.menu.main]]
name = "Products"
url = "products/"
weight = "4"

[[languages.en.menu.main]]
name = "Services"
url = "services/"
weight = "5"

[[languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = "6"

[[languages.en.menu.main]]
name = "Appointment"
url = "https://squareup.com/appointments/book/lkzsutw147ekig/LS5KRH7VEZTBB/services"
weight = "7"